apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      {{ .Values.configmap.data }}
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }
spec:
  replicas: {{ .Values.replicaCount }
  selector:
    matchLabels:
      {{ .Values.configmap.data }}
  strategy:
    rollingUpdate:
      maxSurge:  {{ .Values.resources.limits.cpu }}
      maxUnavailable: {{ .Values.resources.limits.memory }}
    type: RollingUpdate
  template:
    metadata:
      labels:
          {{ .Values.configmap.data }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        name: nginx-alpine
