apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.configmap.data }}
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: 8111
  selector:
    app: nginx
    tag: alpine
  type: {{ .Values.service.type }} 
