namespace:
  name: staging

replicaCount: 1
image:
  repository: pixelpotato/nginx:alpine 
  tag: 1.18.0 
  pullPolicy: IfNotPresent

resources: 
  requests:
     cpu: 50m
     memory: 128Mi

configmap:
  data: "version: 1.18.0"

Service:
  type: ClusterIP
  port: 8111
