namespace:
  name: demo
image:
  repository: pixelpotato/nginx:alpine 
  tag: v1.0.0
  pullPolicy: IfNotPresent

Service:
  type: ClusterIP
  port: 8111

replicaCount: 3

resources: 
  requests:
     cpu: 50m
     memory: 256Mi

configmap:
  data: "version: alpine"